### PR TITLE
added breadcumbs to the student waysofbeing

### PR DESCRIPTION
**Pull request by Zmuse001**
### Changes
added breadcrumbs to student waysofbeing and linked them to various pages

### Comments, Notes, or  Questions
This section is if you want to share something related to the PR with the reviewer. 

### Related Screenshots 

Screenshot 2024-05-28 at 12 17 58 PM

### Before you submit for review, Did you...

- [ ] Added relevant tests (if applicable)
- [ ] Linked Asana ticket to PR
- [ ] Added comments, notes, or questions for reviewwer
- [ ] Added relevant screenshots
- [ ] Ensured ticket title is clear and concise(i.e. 'Donation Form Feature' instead of 'sfg/chels/donation-form'

### CODE REVIEW

**Review by Jcvang5 — APPROVED** [review]
Looks good to me, great job!

**Comment by ridwvn22** [comment]
Screenshot 2024-05-28 at 12 36 26 PM

looks good, I am not seeing an error.

**Comment by ridwvn22** [comment]
Screenshot 2024-05-28 at 2 48 50 PM

looks good, no error

**Comment by Zmuse001** [comment]
> Screenshot 2024-05-28 at 2 48 50 PM
> looks good, no error

wrong ticket, go to the identify buttone ticket

**Review by edithemmings — APPROVED** [review]
Looks good nice work!

**Pull request merged**
