### PR TITLE
Breadcrumb added to Knowing_categories - Mustafe

### PR DESCRIPTION
**Pull request by Muste8**
### Changes
Give a short summary of the changes made in this PR. 
-Added breadcrumb to knowingcategories
-Breadcrumb successfully links parent(?) views

### Link to Issue 
Link Asana ticket here!
https://app.asana.com/0/1206866992204663/1207247077375569/f
### Comments, Notes, or  Questions
This section is if you want to share something related to the PR with the reviewer. 

### Related Screenshots 
For FE tickets specifcially, please include a screenshot of your work!

Screenshot 2024-05-21 at 12 21 37 PM

### Before you submit for review, Did you...

- [x] Added relevant tests (if applicable)
- [x] Linked Asana ticket to PR
- [x] Added comments, notes, or questions for reviewwer
- [x] Added relevant screenshots
- [x] Ensured ticket title is clear and concise(i.e. 'Donation Form Feature' instead of 'sfg/chels/donation-form'

### CODE REVIEW

**Comment by ridwvn22** [comment]
Screenshot 2024-05-21 at 3 38 54 PM
looks great!

**Review by ridwvn22 — APPROVED** [review]

**Comment by edithemmings** [comment]
Screenshot 2024-05-21 at 3 57 07 PM
^Looks like from the mockups it should be "What I Know"

**Comment by Muste8** [comment]
Updated breadcrumb
Screenshot 2024-05-21 at 4 06 16 PM

**Comment by Muste8** [comment]
> Screenshot 2024-05-21 at 3 57 07 PM
> ^Looks like from the mockups it should be "What I Know"

Should I also update 'students' to 'My Students'

**Review by ridwvn22 — APPROVED** [review]
good!

**Pull request merged**
