### PR TITLE
Sidebar margin issue fixed - Mustafe

### PR DESCRIPTION
**Pull request by Muste8**
### Changes
Give a short summary of the changes made in this PR. 
-Removed unnecessary margin

### Link to Issue 
Link Asana ticket here!

### Comments, Notes, or  Questions
This section is if you want to share something related to the PR with the reviewer. 

### Related Screenshots 
For FE tickets specifcially, please include a screenshot of your work!

https://github.com/softwareforgood/innocent_tech_app/assets/147085122/76214fea-2eb5-4215-a6a5-44b165b3310a

### Before you submit for review, Did you...

- [ ] Added relevant tests (if applicable)
- [ ] Linked Asana ticket to PR
- [ ] Added comments, notes, or questions for reviewwer
- [ ] Added relevant screenshots
- [ ] Ensured ticket title is clear and concise(i.e. 'Donation Form Feature' instead of 'sfg/chels/donation-form'

### CODE REVIEW

**Review by edithemmings — COMMENTED** [review]
Looks better, but still not filling out the full height, and the corners got rounded. The expanded sidebar should look the same as it did before the change.

Screenshot 2024-04-29 at 1 24 54 PM

**Review by edithemmings — COMMENTED** [review]
I made a branch `sidebar-pre-collapse` in case you need a reference for how it looked before

**Comment by Muste8** [comment]
> Looks really good! I noticed one more thing that changed from the original with the position being relative instead of sticky. Ultimately, we want to be able to scroll down long pages without the sidebar scrolling up with it
> 
> Kapture 2024-04-29 at 16 17 08 [ Kapture 2024-04-29 at 16 17 08 ](https://private-user-images.githubusercontent.com/47989172/326590308-682927a0-9ff7-4364-8af4-8bf67a2ebf16.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MjYzODQsIm5iZiI6MTcxNDQyNjA4NCwicGF0aCI6Ii80Nzk4OTE3Mi8zMjY1OTAzMDgtNjgyOTI3YTAtOWZmNy00MzY0LThhZjQtOGJmNjdhMmViZjE2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDIxMjgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkM2VhMjQyYjljNDgwZTQzODljMjM3ODA2YjA4N2I3Y2Q5MmY1NTNmMDk2YjZhZDZlZjI1ODIwOTRjMDQ4YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t2r5rLr-XTjFiM50LFvaDECdEhgeSOSTDIzJP2DmhxY) [ ](https://private-user-images.githubusercontent.com/47989172/326590308-682927a0-9ff7-4364-8af4-8bf67a2ebf16.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MjYzODQsIm5iZiI6MTcxNDQyNjA4NCwicGF0aCI6Ii80Nzk4OTE3Mi8zMjY1OTAzMDgtNjgyOTI3YTAtOWZmNy00MzY0LThhZjQtOGJmNjdhMmViZjE2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDIxMjgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkM2VhMjQyYjljNDgwZTQzODljMjM3ODA2YjA4N2I3Y2Q5MmY1NTNmMDk2YjZhZDZlZjI1ODIwOTRjMDQ4YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t2r5rLr-XTjFiM50LFvaDECdEhgeSOSTDIzJP2DmhxY)

That is a good point!

**Review by edithemmings — APPROVED** [review]
Looks great Mustafe!! Nice work 🚀

**Pull request merged**
