### PR TITLE
single active student focus

### PR DESCRIPTION
**Pull request by AynAhmed**
### Changes
Give a short summary of the changes made in this PR. 

Wrote tests and logic to ensure that a student is only able to have a 
single active studentFocus at any given time. 

### Link to Issue 
Link Asana ticket here!
https://app.asana.com/0/1206867754125042/1207303577468853/f

### Comments, Notes, or  Questions
This section is if you want to share something related to the PR with the reviewer. 

### Related Screenshots 
For FE tickets specifcially, please include a screenshot of your work!
Successful Test ->
Screenshot 2024-05-21 at 5 08 30 PM

### Before you submit for review, Did you...

- [x] Added relevant tests (if applicable)
- [x] Linked Asana ticket to PR
- [x] Added comments, notes, or questions for reviewwer
- [x] Added relevant screenshots
- [x] Ensured ticket title is clear and concise(i.e. 'Donation Form Feature' instead of 'sfg/chels/donation-form'

### CODE REVIEW

**Review by KNAthari — APPROVED** [review]

**Review by edithemmings — COMMENTED** [review]
Looking great! Your test covers one of the AC for your ticket ("If a student gets a new focus, then it becomes the single active focus"), but there are two more that I'm not seeing covered:

- "If someone tries to update the one active focus to inactive, then we should get an error"
- "If the student gets a new focus that they already have an inactive student_focus for, then the existing student_focus gets updated to active (ie a new student focus is NOT created)"

**Comment by edithemmings** [comment]
Gave a demo of what some cleanup could look like here. Please hmu if you'd like to chat about it! https://github.com/softwareforgood/innocent_tech_app/pull/132

**Comment by edithemmings** [comment]
Looks like it needs some cleanup to appease rubocop

**Comment by AynAhmed** [comment]
> Looks like it needs some cleanup to appease rubocop

Done

**Review by KNAthari — APPROVED** [review]
This looks good

**Review by edithemmings — APPROVED** [review]
Looks so good!! Nice work with really tricky model logic.

**Pull request merged**
