### PR TITLE
bugfix for breadcrumb links - Mustafe

### PR DESCRIPTION
**Pull request by Muste8**
### Changes
Give a short summary of the changes made in this PR. 
- Added a bug fix for students index buttons when navigating from breadcrumbs

### Link to Issue 
Link Asana ticket here!
https://app.asana.com/0/1206866992204663/1207423220707143/f
### Comments, Notes, or  Questions
This section is if you want to share something related to the PR with the reviewer. 
- data: {turbo: false } didn't work for me at first until I realized that I forgot the ":" after turbo

### Related Screenshots 
For FE tickets specifcially, please include a screenshot of your work!

https://github.com/softwareforgood/innocent_tech_app/assets/147085122/785701f5-92ce-40db-8709-6954b3814423

### Before you submit for review, Did you...

- [x] Added relevant tests (if applicable)
- [x] Linked Asana ticket to PR
- [x] Added comments, notes, or questions for reviewwer
- [x] Added relevant screenshots
- [x] Ensured ticket title is clear and concise(i.e. 'Donation Form Feature' instead of 'sfg/chels/donation-form'

### CODE REVIEW

**Review by asmanoor17 — APPROVED** [review]
looks good! works as expected! thank you for fixing that.

**Review by edithemmings — COMMENTED** [review]
Hmm it becomes a little cumbersome if we have to make sure to disable turbo every time we add a new link to the student show page. Did you look into the original javascript interaction at all to see if there were opportunities there for improving it?

**Comment by Muste8** [comment]
> Hmm it becomes a little cumbersome if we have to make sure to disable turbo every time we add a new link to the student show page. Did you look into the original javascript interaction at all to see if there were opportunities there for improving it?

Unfortunately, I have not messed with the Javascript too much

**Comment by Muste8** [comment]
I found an elegant solution by digging around Stackoverflow by adding this to application.html.erb and it works

`<meta name="turbo-visit-control" content="reload">`

**Review by asmanoor17 — DISMISSED** [review]

**Review by edithemmings — APPROVED** [review]
Nice refactor!! Works like a charm 👌

**Review by crestu — COMMENTED** [review]
https://github.com/softwareforgood/innocent_tech_app/assets/143304087/6ba4bc8b-314e-4af9-a7db-d160b74b46d3

for some reason its still only working on refresh from my end

**Pull request merged**
