### PR TITLE
Select active focus in focus form

### PR DESCRIPTION
**Pull request by Jcvang5**
### Changes
The active focus is now selected when looking at the focus form, and none selected if there is no active focus.

### Link to Issue 
[Link Asana ticket here!
](https://app.asana.com/0/1206510424537042/1207303577468855)
### Comments, Notes, or  Questions
This section is if you want to share something related to the PR with the reviewer. 

### Related Screenshots 

https://github.com/softwareforgood/innocent_tech_app/assets/143450521/2cca7b53-ac0d-4bb5-99f2-8228e2a8ed39

### Before you submit for review, Did you...

- [x] Added relevant tests (if applicable)
- [x] Linked Asana ticket to PR
- [x] Added comments, notes, or questions for reviewwer
- [x] Added relevant screenshots
- [x] Ensured ticket title is clear and concise(i.e. 'Donation Form Feature' instead of 'sfg/chels/donation-form'

### CODE REVIEW

**Comment by edithemmings** [comment]
Could you attach a screen recording? I was seeing some goofy behavior when I pulled it

**Review by KNAthari — APPROVED** [review]
It is working on my end.

**Comment by Jcvang5** [comment]
> Could you attach a screen recording? I was seeing some goofy behavior when I pulled it


https://github.com/softwareforgood/innocent_tech_app/assets/143450521/c2c466e9-c2ea-4bca-a12a-387380c6f0db

**Review by edithemmings — COMMENTED** [review]
What happens when you try to update it and submit the form?

**Review by edithemmings — APPROVED** [review]
It's working for me now! I think I was getting validation errors due to my local data setup. Seems like an existing issue with the controller. I made a [separate ticket](https://app.asana.com/0/1206510424537042/1207402904822351). Nice work!!
Kapture 2024-05-24 at 10 08 03

**Comment by Jcvang5** [comment]
> What happens when you try to update it and submit the form?

It should update it in the database as well

**Pull request merged**
