### PR TITLE
Updated student show page + Partials

### PR DESCRIPTION
**Pull request by Jcvang5**
### Changes
Updated student show, created partials, styling student show page

### Link to Issue 
(https://app.asana.com/0/inbox/1206867754422804)
### Comments, Notes, or  Questions
This section is if you want to share something related to the PR with the reviewer. 

### Related Screenshots 
For FE tickets specifcially, please include a screenshot of your work!
image

### Before you submit for review, Did you...

- [x] Added relevant tests (if applicable)
- [x] Linked Asana ticket to PR
- [x] Added comments, notes, or questions for reviewwer
- [x] Added relevant screenshots
- [x] Ensured ticket title is clear and concise(i.e. 'Donation Form Feature' instead of 'sfg/chels/donation-form'

### CODE REVIEW

**Comment by Jcvang5** [comment]
I also created this as a draft pull request, but I think I accidentally clicked on ready for review which turned it into a regular pull request.

**Comment by camckin10** [comment]
@Jcvang5  This looks good for a first pass! 

Comments below: 

- "_Also not able to push the strategies sidebar more to the right, I tried updating the margins + padding and it did not work. **I was also unable to make it taller as well, I was able to make changes to it and it did update it when I updated the code in the console, but not when I tried to make the same changes is VSC.**_"

☝️  So you were able to make the change in the console, but you didn't make the changes in your text editor?  If the changes in the console were successful, then I would like to see those changes mirrored in the code as well. 

- You were unable to make the 'Connect' button align with the student icon because you added that button code inside a partial. When you render the connect partial on the student show page, you're  only rendering the content in the partial. Have you tried adding the connect button *directly* to the show page for **now** to test how to align that button with the image?

**Comment by Jcvang5** [comment]
> @Jcvang5 This looks good for a first pass!
> 
> Comments below:
> 
> * "_Also not able to push the strategies sidebar more to the right, I tried updating the margins + padding and it did not work. **I was also unable to make it taller as well, I was able to make changes to it and it did update it when I updated the code in the console, but not when I tried to make the same changes is VSC.**_"
> 
> ☝️ So you were able to make the change in the console, but you didn't make the changes in your text editor? If the changes in the console were successful, then I would like to see those changes mirrored in the code as well.
> 
> * You were unable to make the 'Connect' button align with the student icon because you added that button code inside a partial. When you render the connect partial on the student show page, you're  only rendering the content in the partial. Have you tried adding the connect button _directly_ to the show page for **now** to test how to align that button with the image?

I was not able to change the margins, but I was able to change the height in the console. I also did try directly adding the connect button in the show page but whenever I would zoom in or out the button would be displaced, so in order to not have the button in a random location, I wanted to keep the code in a partial until I was able to find a solution

**Review by edithemmings — COMMENTED** [review]
Looks fantastic! I'm good to merge in the name of progress over perfection, but I'll leave the final stamp of approval to Chelsey since they left a request on there.

**Review by camckin10 — APPROVED** [review]
Excellent work @Jcvang5 ! 
Happy that you had  some breakthroughs! 

Before merging into main please: 
--Make sure ticket description is up to date
--resolve any conversations on your PR. 
--merge into main and see how test suite runs(fix bugs, if any)

**Pull request merged**
