### PR TITLE
Unlock Student Knowing View

### PR DESCRIPTION
**Pull request by crestu**
### Changes
created new route for the unlock view. created an unlocked partial that contains a message wrapped a conditional

### Link to Issue 
https://app.asana.com/0/1206867754300740/1207170882740319

### Related Screenshots 
Screenshot 2024-05-22 at 2 27 34 PM

### Before you submit for review, Did you...

- [X] Added relevant tests (if applicable)
- [X] Linked Asana ticket to PR
- [X] Added comments, notes, or questions for reviewwer
- [X] Added relevant screenshots
- [X] Ensured ticket title is clear and concise(i.e. 'Donation Form Feature' instead of 'sfg/chels/donation-form'

### CODE REVIEW

**Comment by crestu** [comment]
> Screenshot 2024-05-22 at 3 26 58 PM
> I see this path, however there is issue that arise when going to the ways of being to get to this path.

i think this is being addressed in a new ticket

**Comment by camckin10** [comment]
@crestu  
A few things: 
1) Fix merge conflicts
2) Mark PR ready for review..its in draft mode currently
3) Tag an apprentice to review your PR

After you worked on those tasks, I can give it another review.

**Review by Jcvang5 — APPROVED** [review]
Working for me and meets AC, good job!

**Review by camckin10 — APPROVED** [review]
Lgtm!

**Pull request merged**
